### ISSUE TITLE
test for null in render

### ISSUE THREAD

**Issue by mitel** [acdlite/react-rx-component#10]
[react beginner here]
running the example at https://github.com/acdlite/redux-rx (TodoConnector), noticed that the render function gets called with props=null. 
modifying createRxComponent to avoid that:

    render() {
      const childProps = this.state;
      const { children } = this.props;

      // avoids rendering the dumb component if childProps is null
      if (!childProps) return null;

      if (typeof render === 'function') {
        return render(childProps);
      }

      if (typeof children === 'function') {
        return children(childProps);
      }
    }

**Comment by acdlite** [comment]
If `childProps` is possibly null, I think that should be handled by the render function.
