### ISSUE TITLE
Rx as an event membrane

### ISSUE THREAD

**Issue by HighOnDrive** [acdlite/react-rx-component#7]
Glad to see greater Rx usage with React. I do not know Rx very well but had looked at the API and decided that it would work well with my idea of flux in my app, which is entirely event driven. Essentially, I just want to capture all input events in React components and forward them to a central hub object. I call this hub the interactor and the thin event capture layer the membrane.

The idea is to process the captured event streams further in the interacter and then have actions/tools receive the events and handle them in their own unique way. What action receives the Rx stream/s is determined by what action happens to be activated. Actions would be transitioned to by another universal picker handler that sets what action is active. Actions then ultimately modify state, which would trigger the re-render of any components listening for such state, bringing the flux flow full circle.

I was thinking this would allow my myriad actions to be abstracted from components and move toward being plugins. Would the react-rx-component be useful for this scenario or is there some other React Rx library that is better suited?

**Comment by HighOnDrive** [comment]
Thanks for no reply, it now appears that Cycle.js.org has provided the answers to my quest :-)

**Comment by acdlite** [comment]
Haha I'm sorry, haven't looked at this project in a while. Cycle is great, glad it is working for you :)
